const en = {
    Announcement: 'ANNOUNCEMENT',
    Announcement_Intro:'Get the latest notifications from your cooperative or farmer business group. Also general announcements on crop protection, crop nutrition and farmer markets.',
    Welcome_Back:'Welcome Back',
    Training_Intro:'Get access to online training modules for different crops and value chains. Training modules have text, images and links to videos to make sure your farming practice is up to date and profitable.',
    Resend_Otp:'Resend Otp',
    Weather_update_Inro:'Get hyper local weather updates. Rain, temperature, humidity, current weather and forecast for your farm so you can plan your farming activities accordingly.',
    Send_Otp:'SEND OTP',
    Male:'Male',
    Female:'Female',
    Edit:'Edit',
    Please_Login_Here:'Please Login Here',
    Please_enter_mobile_number_here:'Please Enter Mobile Number Here',
    Recover_Password:'Recover Password',
    Skip:'Skip',
    Forgot_Password:'Forgot Password',
    Get_Started:'GET STARTED',
    Age:'Age',
    Training: 'TRAINING',
    Weather_update: 'WEATHER UPDATE',
    Login: 'LOGIN',
    Sign_up: 'SIGN UP',
    As_a_member_of_cooperative: 'AS A MEMBER OF COOPERATIVE',
    As_an_individual: 'AS AN INDIVIDUAL',
    As_a_member_of_cooperative_Small: 'As a member of cooperative',
    As_an_individual_Small: 'As an individual',
    Mobile: 'Mobile',
    Title_here:'Title here',
    Select_here:'Select here',
    Password: 'Password',
    Change: 'CHANGE',
    Change_password: 'CHANGE PASSWORD',
    Confirm_password: 'Confirm password',
    Dont_have_an_account: 'Don’t have an account',
    Sign_up_here: 'Sign up here',
    Welcome: 'WELCOME',
    Enter_Otp:'Enter Otp',
    Ask_and_agronomist: 'ASK AN AGRONOMIST',
    Commodity_market: 'COMMODITY MARKET',
    Farm_Records: 'FARM RECORD',
    All_items: 'All Items',
    Recent: 'Recent',
    Old: 'Old',
    Take_test: 'TAKE TEST',
    Question: 'Question',
    QuestionD: 'Question',
    to: 'To',
    Download: 'DOWNLOAD',
    Submit: 'SUBMIT',
    Result: 'Result',
    You_have_completed: 'You have Completed',
    out_of: 'out of',
    You_score: 'You Score',
    Pass: 'Pass',
    Fail: 'Fail',
    Ask_your_question: 'Ask Your Question',
    Type_here: 'Type here',
    Upload_image: 'Upload Image',
    Upload_here: 'Upload Here',
    My_questions: 'MY QUESTIONS',
    My_questions_Small: 'My Questions',
    Other_questions: 'Other Questions',
    You_have_10_answers: 'You have 10 answers',
    Weather: 'WEATHER',
    Location: 'Location',
    Description: 'Description',
    Add_price: 'Add Price',
    Upload_image: 'Upload Image',
    Date: 'Date',
    Add_record: 'ADD RECORD',
    Download_file: 'DOWNLOAD FILE',
    To: 'To',
    From: 'From',
    Notifications: 'NOTIFICATIONS',
    Today: 'Today',
    Previous_notifications: 'Previous notifications',
    Profile: 'PROFILE',
    Profile_Small: 'Profile',
    Name: 'Name',
    Gender: 'Gender',
    Mobile: 'Mobile Number',
    Email: 'Email',
    Settings: 'SETTINGS',
    Edit_profile: 'Edit Profile',
    Change_password_Small: 'Change password',
    Notification: 'Notification',
    Regional: 'Regional',
    Language: 'Language',
    About: 'About',
    Logout: 'Logout',
    Current_password: 'Current Password',
    New_password: 'New Password',
    Confirm_password: 'Confirm Password',
    Reset_button: 'RESET',
    ABOUT:'ABOUT',
    About_Content:'FarmKonnect is a product of Lentera Africa, supporting farmers in Africa with digital farm extension services. Developed in collaboration with CEFA NGO Kenya and Cooperation and Development NGO, Uganda.'

}
const sw = {
    Announcement: 'Matangazo',
    Announcement_Intro:"Pata matangazo kutoka kwa ushirika wako au kikundi cha ukulima. Pata pia matangazo kuhusu ukuzaji wa mimea na julishwa kunapotokea wadudu au magonjwa yanaodhuru mimea yako",
    Welcome_Back:'Karibu tena',
    Training_Intro:'Pata masomo yatakayo imarisha shamba yako. Ujuzi wa kisasa kuhakikisha unapata faida kwa shamba lako.',
    Male:'Mwanaume',
    Weather_update_Inro:'Pata ujumbe kuhusu hali ya hewa katika eneo lako. pata Utabiri wa joto, mvua, unyevu na upepo, ili uweke mikakati maalum katika shamba lako.',
    Female:'Mwanamke',
    Please_Login_Here:'Tafadhali Ingia hapa',
    Please_enter_mobile_number_here:'Tafadhali weka nambari ya simu hapa',
    Recover_Password:'Rejesha Nenosiri',
    Enter_Otp:'Ingiza Otp',
    Resend_Otp:'Tuma tena Otp',
    Send_Otp:'Tuma OTP',
    Age:'Umri',
    Edit:'Hariri',
    Get_Started:'Anza',
    Forgot_Password:'Umesahau Nywila',
    Skip:'Ruka',
    Training: 'Masomo',
    Weather_update: 'Hali ya hewa',
    Title_here:'kichwa hapa',
    Select_here:'chagua hapa',
    Login: 'Ingia',
    Sign_up: 'Jisajili',
    As_a_member_of_cooperative: 'Kama memba wa kikundi au ushirika',
    As_an_individual: 'Mkulima binafsi',
    As_a_member_of_cooperative_Small: 'Kama memba wa kikundi au ushirika',
    As_an_individual_Small: 'Mkulima binafsi',
    Mobile: 'Nambari ya simu',
    Password: 'Nenosiri',
    Change: 'Badilisha',
    Change_password: 'Badilisha neno siri',
    Confirm_password: 'Hakikisha neno siri',
    Dont_have_an_account: 'Hauna akaunti',
    Sign_up_here: 'Jisajili hapa',
    Welcome: 'Karibu',
    Ask_and_agronomist: 'Uliza mtaalamu',
    Commodity_market: 'Soko ya bidhaa',
    Farm_Records: 'Rekodi za shamba',
    All_items: 'matangazo yote',
    Recent: 'Hivi karibuni',
    Old: 'Ya zamani',
    Take_test: 'Anza zoezi',
    Question: 'Swali',
    QuestionD: '',
    to: 'hadi',
    Download: 'Pakua',
    Submit: 'Wasilisha',
    Result: 'Matokeo',
    You_have_completed: 'Umekamilisha maswali',
    out_of: 'kati ya maswali',
    You_score: 'Alama yako',
    Pass: 'Umefaulu',
    Fail: 'Umefeli',
    Ask_your_question: 'Uliza swali yako',
    Type_here: 'Andika hapa',
    Upload_image: 'Pakia picha',
    Upload_here: 'Pakia hapa',
    My_questions: 'Maswali yangu',
    My_questions_Small: 'Maswali yangu',
    Other_questions: 'Maswali mengine',
    You_have_10_answers: 'Uko na majibu 10',
    Weather: 'Hali ya hewa',
    Location: 'Eneo',
    Description: 'Maelezo',
    Add_price: 'Weka bei',
    Upload_image: 'Pakia picha',
    Date: 'Tarehe',
    Add_record: 'Wasilisha rekodi',
    Download_file: 'Pakua faili',
    To: 'Hadi',
    From: 'Kutoka',
    Notifications: 'Arifa',
    Today: 'Leo',
    Previous_notifications: 'Arifa za awali',
    Profile: 'Wasifu wa mtumiaji',
    Profile_Small: 'Wasifu wa mtumiaji',
    Name: 'Jina',
    Gender: 'Jinsia',
    Mobile: 'Nambari ya simu',
    Email: 'Barua pepe',
    Settings: 'Mipangilio',
    Edit_profile: 'Badilisha wasifu wa mtumiaji',
    Change_password_Small: 'Badilisha neno siri',
    Notification: 'Arifa',
    Regional: 'Eneo',
    Language: 'Lugha',
    About: 'Kuhusu hii app',
    Logout: 'Ondoka',
    Current_password: 'Nenosiri la sasa',
    New_password: 'Nenosiri mpya',
    Confirm_password: 'Hakikisha nenosiri',
    Reset_button: 'Wasilisha',
    ABOUT:'Kuhusu Hii App',
    About_Content:'FarmKonnect ni app ya Lentera Africa, inayosaidia wakulima barani Afrika na huduma za ugani za kilimo za kidijitali. Imeandaliwa kwa ushirikiano na CEFA NGO Kenya na NGO ya Ushirikiano na Maendeleo, Cooperation and Development, Uganda.'


}
export { en, sw }